### ISSUE TITLE
How to run on shared host?

### ISSUE THREAD

**Issue by petrk94** [Cryde/php-vote#16]
Hello,
I really like the project, but Im unable to get it run on my shared host.
I have cloned the repo to a subdomain and wanted to start the bin/console server:start, but how to access it on a domain?

Is it already production ready or only on local machines?
I would like to use it for community communication and important ideas/problems to talk and discuss about.

Thanks

**Comment by Cryde** [comment]
It's possible to install this project on shared host but not recommended at all (really).
```bin/console server:start``` command is only for dev purpose

It's production ready (see [https://php-vote.com](https://php-vote.com)) but on shared host you will encounter problems : 
- not able to build the cache
- not able to install vendor
- not able to run migrations (db)
- not able to set ENV var
- not able to  run the build of  the assets

Some Symfony doc about that : https://symfony.com/doc/current/deployment.html
I strongly recommend you to use a service listed on the doc or use a server with ssh access.

**Comment by petrk94** [comment]
@Cryde
Thanks for your response.
No that's not a problem for my shared host. I can install PHP composer vendor etc. This works. Node works too without problems. I have SSH and mariadb access (phpmyadmin), I have set .env file. I have run the compile process, but after it's compiling, it doesn't proceed and nothing happens. After the message appear that the compilation took x seconds. I have killed the process and started the phone development server, but it doesn't worked.

**Comment by Cryde** [comment]
I'm not doing deployment by hand... Sorry I use deployer [https://deployer.org/
](https://deployer.org/)
It does everything for me automatically (it does it via ssh)

Here is my config file for deployer (`deployer.php`) : 
```php
<?php

namespace Deployer;

require 'recipe/symfony4.php';
require 'vendor/deployer/recipes/recipe/npm.php';

// Project repository
set('repository', 'git@github.com:Cryde/php-vote.git');

// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', true);
set('keep_releases', 1);
set('ssh_multiplexing', true);

// Hosts
inventory('hosts.yml');

set(
    'env',
    function () {
        return [
            'APP_ENV'      => get('APP_ENV'),
            'DATABASE_URL' => get('DATABASE_URL'),
            'APP_SECRET'   => get('APP_SECRET'),
        ];
    }
);

// Tasks
desc('Build assets');
task(
    'assets:build',
    function () {
        run('cd {{release_path}} && {{bin/npm}} run build');
    }
);
after('npm:install', 'assets:build');

desc('Remove node_modules folder');
task(
    'assets:clean',
    function () {
        run('cd {{release_path}} && rm -rf node_modules');
    }
);
after('deploy:symlink', 'assets:clean');

desc('Restart PHP-FPM service');
task(
    'php-fpm:restart',
    function () {
        run('sudo service php7.2-fpm reload');
    }
);
after('deploy:symlink', 'php-fpm:restart');

// Migrate database before symlink new release.
before('deploy:symlink', 'database:migrate');
after('deploy:update_code', 'npm:install');
```

And here an example of `hosts.yml`
```
phpvote:
  hostname: host_of_ssh_or_ip
  user: ssh_user
  deploy_path: /path/to/your/root/dir/
  APP_ENV: prod
  APP_SECRET: random_app_secret
  DATABASE_URL: mysql://db_user_name:password@host_or_ip:port/db_name
  MAILER_URL: mailer_url_here
  GITHUB_CLIENT_ID: client_id_here
  GITHUB_CLIENT_SECRET: client_key_here
```

**Comment by petrk94** [comment]
ah ok, can you guide me how to get it deployed with deployer?
When Im in the subdomain phpvote.xxx.de, I run composer require deployer/deployer and it will be saved in vendor/deployer/*
How to get it run?

Thanks

**Comment by Cryde** [comment]
Deployer will help you to deploy it from your computer to your server.

**Comment by petrk94** [comment]
@Cryde 
Ok, I will try it, Im run windows, so just download the repo and init deployer in the downloaded repo?
Then follow the instruction?
